---
- name: Deploy .env configuration
  ansible.builtin.template:
    src: env.j2
    dest: "{{ healthchecks_install_dir }}/.env"
    owner: "{{ healthchecks_user }}"
    group: "{{ healthchecks_group }}"
    mode: "0640"
  notify: restart healthchecks

- name: Deploy uwsgi.ini
  ansible.builtin.template:
    src: uwsgi.ini.j2
    dest: "{{ healthchecks_install_dir }}/uwsgi.ini"
    owner: "{{ healthchecks_user }}"
    group: "{{ healthchecks_group }}"
    mode: "0644"
  notify: restart healthchecks
